### ISSUE TITLE
Migrate from `traverse` to `neotraverse`

### ISSUE THREAD

**Issue by trivikr** [textlint/textlint-plugin-html#27]
# Description

The [Ecosystem Performance](https://e18e.dev/) was formed in July 2024 to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

On the e18e cleanup channel on Discord, multiple solutions are being discussed. One of them is to replace `traverse` with `neotraverse`, which reduces install size by around 3.5 MB and number of dependencies by 65.
For details, check blog post https://puruvj.dev/blog/forking-and-fixing-traverse

The textlint/textlint-plugin-html depends on traverse
https://github.com/textlint/textlint-plugin-html/blob/9e9efa66db3575d3973e758e0d3e598dad6977a3/package.json#L54

## Additional Data

There's a codemod available in https://github.com/es-tooling/module-replacements-codemods to migrate from traverse to neotraverse

**Comment by azu** [comment]
Related https://github.com/textlint/textlint/issues/1400
